# Generated by Django 3.0.4 on 2020-04-20 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20200415_1854'),
        ('recipes', '0007_auto_20200406_1451'),
    ]

    operations = [
    ]
