# Generated by Django 3.0.4 on 2020-05-15 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20200406_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='country',
            field=models.CharField(default=(0, 0), max_length=50),
        ),
    ]
