# Generated by Django 3.0.5 on 2020-05-20 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_merge_20200420_1639'),
        ('recipes', '0009_recipe_made_by'),
    ]

    operations = [
    ]
